export enum ActionType {
    SetStoredOptions,
    SetInitialData,
    SetReviewsData,
    SetLoyaltyData,
    SetVMSData,
    SetSubscriptionData,
    setReviewsCountsAndData,
    SetLoyaltyInstances,
    SetLoyaltyCampaigns,
    SetLoyaltyRedemptions,
    SetLoyaltyVipTiers,
    SetInstalledLoylatyModules,
    SetCustomerDetails,
    SetIsUpdateAllURLsModalOpen,
    UpdateDataManually,
    AddAccountToList,
    RemoveAccountFromList
}
